version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: ztna_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ztna_db
      MYSQL_USER: ztna_user
      MYSQL_PASSWORD: ztnapassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ztna-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  uem-server:
    build: ./uem-server
    container_name: ztna_uem_server
    #ports:
    #  - "8000:8000" #for debugging
    networks:
      - ztna-net

  backend:
    build: ./backend
    container_name: ztna_backend
    volumes:
      - ./nginx/conf.d:/nginx_conf_d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_URL: "mysql+pymysql://ztna_user:ztnapassword@db:3306/ztna_db"
      UEM_URL: "http://uem-server:8000"
      NGINX_CONTAINER_NAME: "ztna_nginx"
      NGINX_CONF_PATH: "/nginx_conf_d"
    depends_on:
      db:
        condition: service_healthy
      uem-server:
        condition: service_started
    networks:
      - ztna-net

  nginx:
    build: ./nginx
    container_name: ztna_nginx
    ports:
      - "83:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - backend
    networks:
      - ztna-net

  nginx-exporter:
    build: ./monitoring/nginx-exporter
    container_name: ztna_nginx_exporter
    environment:
      LOG_PATH: /var/log/nginx/access.log
      LISTEN_PORT: "9113"
      GEOIP_DB_PATH: /etc/geoip/GeoLite2-City.mmdb
    volumes:
      - ./nginx/log:/var/log/nginx:ro
      - ./monitoring/geoip:/etc/geoip:ro
    depends_on:
      - nginx
    networks:
      - ztna-net

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: ztna_prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - nginx-exporter
    networks:
      - ztna-net

  grafana:
    image: grafana/grafana:11.1.0
    container_name: ztna_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/nginx-monitoring.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - ztna-net

volumes:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  ztna-net:
    driver: bridge
